package com.optinet.domain.model;

import java.util.UUID;

/**
 * Represents a network element's KPI (Key Performance Indicator) measurement.
 * 
 * A KPI is a quantifiable metric generated by a network element at a specific point in time.
 * Examples: Signal-to-Noise Ratio, Bit Error Rate, Optical Power, Temperature.
 * 
 * Using Java 17+ record for immutability and conciseness.
 */
public record KpiMetric(
    String metricId,              // UUID: unique identifier for this measurement
    String neId,                  // Foreign key: which network element generated this
    KpiType kpiType,              // Type of metric (SNR, BER, POWER, etc.)
    double value,                 // Measured value (numeric)
    String unit,                  // Unit of measurement (dB, bits/sec, mW, etc.)
    long timestamp,               // When measured (Unix milliseconds)
    KpiThresholdStatus thresholdStatus  // NORMAL, WARNING, CRITICAL
) {
    
    /**
     * Create a new KPI metric with auto-generated ID.
     */
    public static KpiMetric create(
        String neId,
        KpiType kpiType,
        double value,
        long timestamp) {
        return new KpiMetric(
            UUID.randomUUID().toString(),
            neId,
            kpiType,
            value,
            kpiType.unit(),
            timestamp,
            KpiThresholdStatus.NORMAL  // Will be evaluated by service
        );
    }
}
